# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.3'
use_frameworks!

target 'eeg-brainwave-client' do
  pod 'Alamofire', '~> 4.7'
  pod 'Charts'
  pod 'PopupDialog', '~> 0.9'
end
